### PR TITLE
Add support for PHP 8.4

### PR DESCRIPTION
**Pull request by acelaya**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | N/A

#### Summary

Add support for PHP 8.4, and run workflows on that version.

### CODE REVIEW

**Comment by acelaya** [comment]
Running psalm on PHP 8.4 seems to fail, and I just realized they [do not officially support](https://github.com/vimeo/psalm/issues/11107) that version yet.

For tests it makes sense to run workflows explicitly for all supported PHP versions, but perhaps you would consider running workflows for static analysis and code checks on a single PHP version?

Otherwise I'm fine keeping this open until psalm supports PHP 8.4 and then update this.

**Comment by veewee** [comment]
Thanks @acelaya 

The changes look fine.

It seems that this repo is still on psalm V4. Bumping to latest 5.x might solve the issue.

Would you mind looking into this? I'm also fine with just merging this one and look at it later.

**Comment by acelaya** [comment]
> Would you mind looking into this?

I can do that. I see the project has a few tools tracked in the `tools` folder. Do you usually update those manually, or are you using something to handle those dependencies?

**Comment by acelaya** [comment]
I downloaded the latest psalm.phar, and it doesn't seem to solve the problem, as the system check still fails.

Additionally, checks fail now with the rest of PHP versions for what I think are probably some changes between versions 4 and 5.

I'll revert this, as it's probably worth tackling the psalm update on its own. You can see the workflow run here https://github.com/veewee/composer-run-parallel/actions/runs/11415978568?pr=12

**Comment by veewee** [comment]
Thanks

**Pull request merged**
